--
-- RagnarokOnline Settings File
-- Generated by RagnarokOnline OpenSetup, Version 2.11.6.397 ( http://ai4rei.net/p/opensetup )
--

-- Workaround for people with broken client folder
-- Note: The client removes this when it saves settings.
--
if OptionInfoList==nil then
	OptionInfoList = {}
end
if CmdOnOffList==nil then
	CmdOnOffList = {}
end
-- End of Workaround


-- Settings
--

OptionInfoList["Trilinear"] = 0
OptionInfoList["Bgm_Volume"] = 100
OptionInfoList["Effect_Volume"] = 100
OptionInfoList["MouseExclusive"] = 0
OptionInfoList["ISFULLSCREENMODE"] = 0
OptionInfoList["WIDTH"] = 800
OptionInfoList["HEIGHT"] = 600
OptionInfoList["BITPERPIXEL"] = 32
OptionInfoList["DEVICECNT"] = 0
OptionInfoList["MODECNT"] = 1
OptionInfoList["SPRITEMODE"] = 2
OptionInfoList["TEXTUREMODE"] = 2
CmdOnOffList["/bgm"] = 1
CmdOnOffList["/sound"] = 1
CmdOnOffList["/notrade"] = 0
CmdOnOffList["/noshift"] = 0
CmdOnOffList["/noctrl"] = 1
CmdOnOffList["/skillfail"] = 1
CmdOnOffList["/notalkmsg"] = 0
CmdOnOffList["/notalkmsg2"] = 0
CmdOnOffList["/showname"] = 0
CmdOnOffList["/fog"] = 1
CmdOnOffList["/aura"] = 1
CmdOnOffList["/window"] = 0
CmdOnOffList["/miss"] = 1
CmdOnOffList["/effect"] = 1
CmdOnOffList["/shopping"] = 1
CmdOnOffList["/stateinfo"] = 1
CmdOnOffList["/loginout"] = 1
CmdOnOffList["/snap"] = 0
CmdOnOffList["/itemsnap"] = 0
CmdOnOffList["/skillsnap"] = 1
CmdOnOffList["/camera"] = 0
CmdOnOffList["/hoai"] = 0
CmdOnOffList["/merai"] = 0
CmdOnOffList["/lightmap"] = 1
CmdOnOffList["/monsterhp"] = 1
CmdOnOffList["/q1"] = 0
CmdOnOffList["/q2"] = 0

-- Preserved client settings
--

